language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.0
      env: TYPO3_VERSION=^8.7

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    echo "Running PHP Coding Standards Fixer checks";
    .Build/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --diff --diff-format=udiff